//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5456
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocketAsyncServer.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSysParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetSysParam();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetSysParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetSysParam(string paramName, string paramValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetContact();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string DeleteContact(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetContact(string contactId, string name, string phone, string group, string mail, string grouppost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetGroup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string Login(string userName, string passWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActiveUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string ActiveUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetPassword(string userName, string oldPws, string newPws);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetTask();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string DeleteTask(string taskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetTask(string taskName, string taskDate, string taskPhone, string taskMessage, string taskPeoples);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetHoliday", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetHoliday();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteHoliday", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string DeleteHoliday(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetHoliday", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetHoliday(string draftID, string draftMonth, string draftDate, string draftName, string draftMessage, string draftType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDraft", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetDraft();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDraft", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string DeleteDraft(string draftID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDraft", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetDraft(string draftID, string draftPhone, string draftMessage, string people);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReceive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetReceive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteReceive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string DeleteReceive(string IDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetReceive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetReceive(string phone, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetSend(string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string DeleteSend(string IDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string InsertSend(string phone, string message, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string UpdateSend(string ID, string status, string msgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhraseGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetPhraseGroup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePhraseGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string DeletePhraseGroup(string IDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPhraseGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetPhraseGroup(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhrase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetPhrase(string groupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePhrase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string DeletePhrase(string IDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetPhrase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetPhrase(string groupID, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetMMS(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMMSFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string GetMMSFile(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetMMS(string mmsID, string phone, string title, string type, string people);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SaveMMS(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SendMMS(string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string DeleteMMS(string IDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SetMail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string SendMail(string fromName, string fromMail, string fromPassword, string toMail, string mailTitle, string mailMain);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSoapChannel : SocketAsyncServer.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SocketAsyncServer.ServiceReference1.ServiceSoap>, SocketAsyncServer.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataTable GetSysParam() {
            return base.Channel.GetSysParam();
        }
        
        public string SetSysParam(string paramName, string paramValue) {
            return base.Channel.SetSysParam(paramName, paramValue);
        }
        
        public System.Data.DataTable GetContact() {
            return base.Channel.GetContact();
        }
        
        public string DeleteContact(string ID) {
            return base.Channel.DeleteContact(ID);
        }
        
        public string SetContact(string contactId, string name, string phone, string group, string mail, string grouppost) {
            return base.Channel.SetContact(contactId, name, phone, group, mail, grouppost);
        }
        
        public System.Data.DataTable GetGroup() {
            return base.Channel.GetGroup();
        }
        
        public string Login(string userName, string passWord) {
            return base.Channel.Login(userName, passWord);
        }
        
        public string ActiveUser(string userName) {
            return base.Channel.ActiveUser(userName);
        }
        
        public string SetPassword(string userName, string oldPws, string newPws) {
            return base.Channel.SetPassword(userName, oldPws, newPws);
        }
        
        public System.Data.DataTable GetTask() {
            return base.Channel.GetTask();
        }
        
        public string DeleteTask(string taskName) {
            return base.Channel.DeleteTask(taskName);
        }
        
        public string SetTask(string taskName, string taskDate, string taskPhone, string taskMessage, string taskPeoples) {
            return base.Channel.SetTask(taskName, taskDate, taskPhone, taskMessage, taskPeoples);
        }
        
        public System.Data.DataTable GetHoliday() {
            return base.Channel.GetHoliday();
        }
        
        public string DeleteHoliday(string id) {
            return base.Channel.DeleteHoliday(id);
        }
        
        public string SetHoliday(string draftID, string draftMonth, string draftDate, string draftName, string draftMessage, string draftType) {
            return base.Channel.SetHoliday(draftID, draftMonth, draftDate, draftName, draftMessage, draftType);
        }
        
        public System.Data.DataTable GetDraft() {
            return base.Channel.GetDraft();
        }
        
        public string DeleteDraft(string draftID) {
            return base.Channel.DeleteDraft(draftID);
        }
        
        public string SetDraft(string draftID, string draftPhone, string draftMessage, string people) {
            return base.Channel.SetDraft(draftID, draftPhone, draftMessage, people);
        }
        
        public System.Data.DataTable GetReceive() {
            return base.Channel.GetReceive();
        }
        
        public string DeleteReceive(string IDs) {
            return base.Channel.DeleteReceive(IDs);
        }
        
        public string SetReceive(string phone, string message) {
            return base.Channel.SetReceive(phone, message);
        }
        
        public System.Data.DataTable GetSend(string status) {
            return base.Channel.GetSend(status);
        }
        
        public string DeleteSend(string IDs) {
            return base.Channel.DeleteSend(IDs);
        }
        
        public string InsertSend(string phone, string message, string status) {
            return base.Channel.InsertSend(phone, message, status);
        }
        
        public string UpdateSend(string ID, string status, string msgID) {
            return base.Channel.UpdateSend(ID, status, msgID);
        }
        
        public System.Data.DataTable GetPhraseGroup() {
            return base.Channel.GetPhraseGroup();
        }
        
        public string DeletePhraseGroup(string IDs) {
            return base.Channel.DeletePhraseGroup(IDs);
        }
        
        public string SetPhraseGroup(string name) {
            return base.Channel.SetPhraseGroup(name);
        }
        
        public System.Data.DataTable GetPhrase(string groupID) {
            return base.Channel.GetPhrase(groupID);
        }
        
        public string DeletePhrase(string IDs) {
            return base.Channel.DeletePhrase(IDs);
        }
        
        public string SetPhrase(string groupID, string message) {
            return base.Channel.SetPhrase(groupID, message);
        }
        
        public System.Data.DataTable GetMMS(string type) {
            return base.Channel.GetMMS(type);
        }
        
        public string GetMMSFile(string ID) {
            return base.Channel.GetMMSFile(ID);
        }
        
        public string SetMMS(string mmsID, string phone, string title, string type, string people) {
            return base.Channel.SetMMS(mmsID, phone, title, type, people);
        }
        
        public string SaveMMS(string ID) {
            return base.Channel.SaveMMS(ID);
        }
        
        public string SendMMS(string ID) {
            return base.Channel.SendMMS(ID);
        }
        
        public string DeleteMMS(string IDs) {
            return base.Channel.DeleteMMS(IDs);
        }
        
        public string SetMail() {
            return base.Channel.SetMail();
        }
        
        public string SendMail(string fromName, string fromMail, string fromPassword, string toMail, string mailTitle, string mailMain) {
            return base.Channel.SendMail(fromName, fromMail, fromPassword, toMail, mailTitle, mailMain);
        }
    }
}
